# This is a basic workflow to help you get started with Actions

name: update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SetUp Python
        uses: actions/setup-python@v2.2.1
        
      - name: Install feedparser
        run: |
          pip3 install feedparser
      
      - name: Update README
        run: |
          python3 updateREADME.py
          
      - name: pull And Push
        run: |-
          git diff
          git config --global user.email "yanglin2042@gmail.com"
          git config --global user.name "kuper"
          git pull
          git add .
          git commit -m "update"
          git push
